Updated picongpu run/env scripts.

diff --git a/picongpu/templates/summit.run.sh.j2 b/picongpu/templates/summit.run.sh.j2
--- a/picongpu/templates/summit.run.sh.j2
+++ b/picongpu/templates/summit.run.sh.j2
@@ -1,12 +1,17 @@
 #!/bin/bash
 
 set -e
-source ../env.sh
-
 echo "Started run.sh"
 
 {% set nprocs = nx*ny*nz %}
 {% set nnodes = (nprocs+5) // 6 %}
+
+source ../env.sh
+
+if [ -z $PROJ ]; then
+    echo "Error: You must set PROJ to your project ID."
+    exit 1
+fi
 
 cat >batch.lsf <<.
 #!/bin/bash
@@ -15,20 +20,20 @@ cat >batch.lsf <<.
 #BSUB -J {{ problem }}
 #BSUB -nnodes {{ nnodes }}
 #BSUB -alloc_flags smt4
-#BSUB -P $proj
+#BSUB -P $PROJ
 #BSUB -o stdout
 #BSUB -e stderr
 
 echo "Started job on \$LSB_HOSTS"
 
+SRUN="jsrun -n {{ nprocs }} -a1 -c7 -g1 -bpacked:7 --smpiargs=-gpu"
+
 # run with using openPMD:
-# jsrun --nrs 6 --tasks_per_rs 1 --cpu_per_rs 7 --gpu_per_rs 1 --latency_priority GPU-CPU --bind rs --smpiargs="-gpu" /gpfs/alpine/proj-shared/csc434/benjha/src/picongpu_tweac_2f2e2374_05032021/simulations/TWEAC_New_Algos_openPMD/tweac_00006gpu_IO_BLOSC2/input/bin/picongpu --mpiDirect --author "benjha <hernandezarb@ornl.gov>" -d 1 3 2 -g 240 816 448 -s 300 --periodic 1 1 1 --openPMD.period 30 --openPMD.file simData --openPMD.ext bp --openPMD.json @../input/etc/picongpu/adios2.json --percent 1 --versionOnce --currentInterpolation none | tee output
+# \$SRUN /gpfs/alpine/proj-shared/csc434/benjha/src/picongpu_tweac_2f2e2374_05032021/simulations/TWEAC_New_Algos_openPMD/tweac_00006gpu_IO_BLOSC2/input/bin/picongpu --mpiDirect --author "benjha <hernandezarb@ornl.gov>" -d 1 3 2 -g 240 816 448 -s 300 --periodic 1 1 1 --openPMD.period 30 --openPMD.file simData --openPMD.ext bp --openPMD.json @../input/etc/picongpu/adios2.json --percent 1 --versionOnce --currentInterpolation none | tee output
 
-
-jsrun -n {{ nprocs }} -a1 -c7 -g1 -bpacked:7 --smpiargs="-gpu" \
-     ../sys/bin/picongpu -d {{nx}} {{ny}} {{nz}} -g {{grid}} --periodic {{periodic}} \
-                         --mpiDirect -s 1000 --percent 1 \
-                         --versionOnce --e_macroParticlesCount.period 50
+\$SRUN ../sys/bin/picongpu -d {{nx}} {{ny}} {{nz}} -g {{grid}} --periodic {{periodic}} \
+                           --mpiDirect -s 1000 --percent 1 \
+                           --versionOnce --e_macroParticlesCount.period 50
 
 echo "COMPLETE"
 .
